### ISSUE TITLE
[Fabric/Quilt] [1.20.1] remaining lives and banReason strings are not being handled properly

### ISSUE THREAD

**Issue by streifen-dev** [iChun/Limited-Lives#15] opened 2023-07-10 01:01 UTC
Strings are not being handled properly and just show the variable name instead of the intended text. Probably applies to all strings but I have tested just the two in the issue title/screenshots 
I am running Fabric/Quilt 1.20.1. I have tested a minimal configuration using only the following setup:

        - completeconfig 2.4.0
        - fabric-api 0.85.0+1.20.1
        - fabricloader 0.14.21
        - java 18
        - limitedlives 1.2.2
        - minecraft 1.20.1

![image](https://github.com/iChun/LimitedLives/assets/86832950/c553cc8a-9aed-48f2-85c7-c90d845df7af)

![image](https://github.com/iChun/LimitedLives/assets/86832950/678e11a5-3c18-4ff3-99da-821dbef818f0)

My config file:

general {
    # Should we announce the player their remaining lives on respawn?
    announceOnRespawn=true
    # Length of time the player is banned (in seconds). Set to 0 to permaban.
    banTime=0
    # Ban type once the player dies too many times.
    # Accepts: SPECTATOR, BAN
    banType=BAN
    # How much health to change per death.
    healthAdjust=-4.0
    # What's the maximum health reduction allowed before it caps out? Set to 0 to disable cap.
    maxHealthReduction=0.0
    # Maximum lives a player can have before being "banned".
    maxLives=5
}

**Comment by iChun** [comment] 2024-01-17 13:43
Sorry for the long wait: I'm working on 1.20.2 currently, and I've fixed the incorrect ban reason, but I can't seem to duplicate the error in the command localisation. I'd like to think LL is installed on the client as well? It is unfortunately needed for localisation.

I will be closing this issue since it's half fixed for the next update/half non-reproducible. If you are still having issues with this in the future please comment or open a new issue

**Closed as completed by iChun** 2024-01-17 13:43 UTC
